### ISSUE TITLE
Search plugin do not loading custom WFS services on Mobile

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8999]
## Description

Using a map with a saved custom search configuration on mobile, the results are not loaded (looks like the default configuration is loaded instead).

As notified in https://groups.google.com/g/mapstore-developers/c/g8wI2sJuEHg

## How to reproduce

-  Load this Map in desktop mode. https://dev-mapstore.geosolutionsgroup.com/mapstore/?#/viewer/openlayers/2464
- Search for "new"
- You will see reults from WFS
- Load the same map from mobile
- 

*Expected Result*
- I have the same results

*Current Result*
- I have results only from Nominatim search

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by buhao75** [comment]
I would like to have this bug fixed in the upcoming release 2023.01.02. I would try to help with the implementation if somebody can give me a hint where to start.

**Comment by tdipisa** [comment]
@buhao75 the version 2023.01.02 will be released this week and this issue has no milestone assigned yet. Therefore I don't think there will be the opportunity to fix/review/test this in time for the new upcoming delivery.
Anyway, if you are interested in contributing for this fix you are welcome. One of our developer will follow to provide you some hints for this. Once the fix is available and tested in master, it will be possible to back-port it to the 2023.01 stable branch while waiting for the next major release in September.

**Comment by offtherailz** [comment]
Hi @buhao75 I took a look to the issue. I created a PR #9329 that fix the bug in general.
It is too late to include this PR in 2023.01.02 **but** I noticed there is an alternative solution that may work for you. 

In `localConfigs.json` --> plugins --> mobile you should add `"SearchServicesConfig",` plugin. 
This will fix the issue, including the code that handles the search configuration, and it apparently do not show the configuration editor anyway on mobile.
So it can be an equivalent solution for your use case, until update to `2023.02.00`. 

Please let us know if this works. 
Bests.

**Comment by buhao75** [comment]
@offtherailz : Thank you very much for your feedback. I will try it out ASAP and let you know..

**Comment by buhao75** [comment]
@offtherailz : I have merged your changes and it works.

**Comment by buhao75** [comment]
@offtherailz : In the meantime I did some intensive testing and might have find some little problem remaining. When I work in mobile context with usersession activated the WFS-Search works in the first time. Then after reloading it doesn't work anymore. After resetting/deleting the usersession it works again. Is it possible that the configuration is not saved in the localstorage?

**Comment by MV88** [comment]
@ElenaGallo testable in DEV
